### ISSUE TITLE
Find all TreeWalker Checks that need to use context strategy

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#100]
All non-TreeWalker checks has been analyzed in https://github.com/checkstyle/patch-filters/issues/21#issuecomment-648743650 and https://github.com/checkstyle/patch-filters/issues/7#issuecomment-659851322. So we also need to find all TreeWalker Checks that need to use context strategy. 

**italics text means that this check has been considered and has context strategy UT.**

**Comment by HuGanghui** [comment]
Need Context Strategy:

Annotation:
- MissingDeprecated
- MissingOverride
- PackageAnnotation
-----
blocks:
- AvoidNestedBlocks
- EmptyBlock
- EmptyCatchBlock
- NeedBraces
- RightCurly (special case next if -> else if)

**Comment by HuGanghui** [comment]
Coding：

1. ArrayTrailingComma (special case , in next line and is deleted)
2. AvoidDoubleBraceInitialization (remove some code like in the first brace private Object o;)
3. AvoidNoArgumentSuperConstructorCall ( super( // violation
        ); -> 10); or vice versa
)
4. CovariantEquals
5. DeclarationOrder （ this is special, because not only need to consider added/patched line below the current but also above the current
6. DefaultComesLast
7. EmptyStatement 
( break 
; 
 Then break removed)
8. EqualsHashCode
9. FallThrough
10. FinalLocalVariable
11. HiddenField
12. MissingCtor
13. MissingSwitchDefault

**Comment by HuGanghui** [comment]
Coding(first letter N-End):

1. NestedForDepth
2. NestedIfDepth
3. NestedTryDepth
4. OverloadMethodsDeclarationOrder
5. PackageDeclaration
6. ReturnCount
7. SimplifyBooleanReturn
8. SuperClone
9. SuperFinalize
10. UnnecessarySemicolonInEnumeration
11. VariableDeclarationUsageDistance

**Comment by HuGanghui** [comment]
Design:

1. DesignForExtension
2. FinalClass
3. HideUtilityClassConstructor
4. InnerTypeLast (previous codes changed/added will affect violation)
5. InterfaceIsType
6. MutableException (previous codes changed/added will affect violation)
7. OneTopLevelClass (previous codes changed/added will affect violation)
8. ThrowsCount

**Comment by HuGanghui** [comment]
Header:
None

**Comment by HuGanghui** [comment]
Import:

1. CustomImportOrder (previous codes changed/added will affect violation)
2. ImportOrder (previous codes changed/added will affect violation)
3. RedundantImport (previous codes changed/added will affect violation)
4. UnusedImports

**Comment by HuGanghui** [comment]
Indentation:

1. CommentsIndentation (previous codes changed/added will affect violation)

**Comment by HuGanghui** [comment]
Metric:

1. ClassDataAbstractionCoupling
2. ClassFanOutComplexity
3. CyclomaticComplexity
4. JavaNCSS
5. NPathComplexity

**Comment by HuGanghui** [comment]
Modifiers:

1. ModifierOrder  (previous codes changed/added will affect violation)

**Comment by HuGanghui** [comment]
Naming:

None

**Comment by HuGanghui** [comment]
Sizes:

1. AnonInnerLength (child node strategy)
2. ExecutableStatementCount (child node strategy)
3. MethodCount (child node strategy)
4. MethodLength (child node strategy)
5. OuterTypeNumber (child node strategy)
6. ParameterNumber (child node strategy)

**Comment by HuGanghui** [comment]
Whitespace:

1. EmptyLineSeparator

**Comment by HuGanghui** [comment]
Miscellaneous:

1. DescendantToken
2. NoCodeInFile (whole file only)
3. OuterTypeFilename

**Comment by rdiachenko** [comment]
@HuGanghui what's the status of this issue?

**Comment by HuGanghui** [comment]
All the checks listed have context UT. This issue can be closed.
