### ISSUE TITLE
Suspicious case: strategy/FileTabCharacter/SingleChangedLine/patchedline/

### ISSUE THREAD

**Issue by romani** [checkstyle/patch-filters#103]
explain violations at https://github.com/checkstyle/patch-filters/pull/95/files#r456474455
there is not violations in newline strategy , but patchedline raise violation on non changed line

**Comment by HuGanghui** [comment]
@romani because this is a changed line, not a added line, so it will appear in patchedline strategy not in newline strategy.

**Comment by romani** [comment]
my bad, I was confused by line number in file - 9, but patch is applied to line 19, so violation is 19 - all good.
