### ISSUE TITLE
Resolve all ignored tests in SuppressionPatchFilterTest

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/patch-filters#104]
Related comment: https://github.com/checkstyle/patch-filters/pull/96/files#r456180795

There are a bunch of ignored tests in `SuppressionPatchFilterTest.java`. They need to be fixed, `@Ignore`s should be removed.

There are two of them:
1) for UniquePropertiesCheck, will be resolved in https://github.com/checkstyle/patch-filters/issues/108 or we need to update Check to report violation on all duplicates (I agree, but filter should still expect Check that place violation in unrelated to change place). There should be few UTs (without new property (mostly suppress all violations) and with property)

2) for RegexpMultilineCheck -  same as above. Violation placed at line where pattern starts, but due to multiline nature, update is done NOT on first line, so Filter should suppress violation if no property from #108 (attention that `id` might be used in such property if user wants).

**Comment by baratali** [comment]
@HuGanghui , please see details about RegexpMultiline in https://github.com/checkstyle/patch-filters/issues/114. (I didn't see this issue before I created #114)

**Comment by romani** [comment]
all tests are active
