### ISSUE TITLE
 SuppressionPatchFilter: mention Translation as non supported Check in javadoc

### ISSUE THREAD

**Issue by romani** [checkstyle/patch-filters#109]
https://checkstyle.org/config_misc.html#Translation

create UT to show how filter can work with this Check when pached files are affected and not.

**Comment by HuGanghui** [comment]
I try to reproduce example in https://checkstyle.org/config_misc.html#Translation_Description. and get the result:

```sh
Starting audit...
[ERROR] /Users/hgh/Downloads/my_file/IDEA_workspace/patchfiltergeneratepatch/src/main/java/Translation/messages_test.properties:1: Key 'hell' missing. [Translation]
[ERROR] /Users/hgh/Downloads/my_file/IDEA_workspace/patchfiltergeneratepatch/src/main/java/Translation/messages_test.properties:1: Key 'ok' missing. [Translation]
[ERROR] /Users/hgh/Downloads/my_file/IDEA_workspace/patchfiltergeneratepatch/src/main/java/Translation/messages_test_de.properties:1: Key 'cancel' missing. [Translation]
[ERROR] /Users/hgh/Downloads/my_file/IDEA_workspace/patchfiltergeneratepatch/src/main/java/Translation/messages_test_de.properties:1: Key 'hello' missing. [Translation]
Audit done.
```

**Comment by romani** [comment]
Nothing we can do about Check decision to make it like this, it just means that this Filter will not support Check and user has to use property `never....`.

**Comment by romani** [comment]
@HuGanghui , please update doc of filter property

`Set has user defined Checks to never suppress if files are touched.`
to
`Set has user defined Checks to never suppress if files are referenced in patch. This property is useful for Checks that place violation on whole file or on not all (first/last) occurrence of cause/violated code. Example: Translation, UniqueProperty, RegexpMultiline`

**Comment by romani** [comment]
Fixed at https://github.com/checkstyle/patch-filters/pull/127
