### ISSUE TITLE
neverSuppressCheck property in case of just removal edits from file

### ISSUE THREAD

**Issue by romani** [checkstyle/patch-filters#125]
neverSuppressCheck is good but it become active if changed file is modified (add/remove lines).

Imagine situation that there is legacy code, it contains tons of violations and user just remove from it some code, for example `System.out.print("ha")`, we will show violation on all instances of `System.out.print("ha")`, but user wanted to do update step by step (not all in ones).

it is not good for Checks instances that search for presence of problematic code.
If there will be a case search for absence of required ... we will violate file properly.

So there is conflict of interests from different Checks. 
should we have something like `alwaysSuppressCheckOnRemoval` ? or smth else ?

**Comment by rdiachenko** [comment]
The problem described above should mostly be solved by https://github.com/checkstyle/patch-filters/issues/302
