### ISSUE TITLE
SuppressionPatchXpathFilter: MissingDeprecated's context strategy

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#131]
SuppressionPatchXpathFilter: MissingDeprecated's context strategy

**Comment by HuGanghui** [comment]
There is a problem is that MissingDeprecated still does not support return AST:

https://github.com/checkstyle/checkstyle/blob/f5cfb9e3c9d141d98bb480c900ebcc320a9f281c/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java#L176

**Comment by rdiachenko** [comment]
The fix was merged.
