### ISSUE TITLE
SuppressionPatchXpathFilter: PackageAnnotation's context strategy

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#135]
SuppressionPatchXpathFilter: PackageAnnotation's context strategy

**Comment by HuGanghui** [comment]
/var/tmp $ cat InputPackageAnnotation.java
```java
package com.puppycrawl.tools.checkstyle.checks.annotation.packageannotation;

@Deprecated
public class InputPackageAnnotation {

}

```
/var/tmp $ cat package-info.java
```java
@Deprecated
package com.puppycrawl.tools.checkstyle.checks.annotation.packageannotation;

```

/var/tmp $ cat config.xml
```xml
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="PackageAnnotation"/>
    </module>

    <!-- as we run on regression even on non-compiled files we need to skip exceptions on them -->
    <module name="SuppressionSingleFilter">
        <property name="message" value="Exception occurred while parsing"/>
        <property name="checks" value="Checker"/>
    </module>

</module>


```
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-8.34-SNAPSHOT-all.jar -c config.xml PackageAnnotation

```sh
Starting audit...
Audit done.
```

**Comment by rdiachenko** [comment]
@HuGanghui please check the case with a violation - https://checkstyle.sourceforge.io/config_annotation.html#PackageAnnotation . It looks like you use a `@Deprecated` annotation in the wrong place within `InputPackageAnnotation.java`, that is why you miss a violation.

**Comment by rdiachenko** [comment]
The fix was merged.
