### ISSUE TITLE
Fix line numbers collection for context strategy

### ISSUE THREAD

**Issue by baratali** [checkstyle/patch-filters#138]
Based on comment https://github.com/checkstyle/patch-filters/pull/120#discussion_r458301397 :

> This will collect all line numbers for all child nodes. Basically we only need start and end for `ast`.
> `start` is line number of `ast` itself and in this method you need to find max line number among `ast`'s children which will be `end`.

**Comment by HuGanghui** [comment]
The fixes were merged.
