### ISSUE TITLE
Do not suppress violations caused by code deletion in context strategy

### ISSUE THREAD

**Issue by baratali** [checkstyle/patch-filters#160]
Now patch-filter processes only new lines and changed lines (INSERT, REPLACE types from jgit). But in some cases deleting code generates new violations for context strategy. 

Example, EmptyCatchBlock:
```java
public class Test {
    public static void main(String[] args) {
        try {
            throw new RuntimeException();
        } catch (RuntimeException e) { // violation context
        }
    }
}
```
patch:
```diff
diff --git a/Test.java b/Test.java
index 1407d82..9edb47a 100644
--- a/Test.java
+++ b/Test.java
@@ -3,8 +3,6 @@ public class Test {
         try {
             throw new RuntimeException();
         } catch (RuntimeException e) { // violation context
-            System.out.println(e);
-            e.printStackTrace();
         }
     }
 }
```
config:
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="EmptyCatchBlock">
            <property name="commentFormat" value="$."/>
        </module>
<!--        <module name="com.puppycrawl.tools.checkstyle.filters.SuppressionPatchXpathFilter">-->
<!--            <property name="file" value="${tp}/defaultContext.patch" />-->
<!--            <property name="strategy" value="context" />-->
<!--        </module>-->
    </module>
</module>
```
expected:
```
Test.java:5:38: Empty catch block.
```
However, when SuppressionPatchXpathFilter is activated (`context` strategy) this violation is suppressed, but it should not be suppressed, because it is caused by code change. (newline and patchedline strategies work correct in this case - they suppress this violation).
Probably, not suppressing on code deletion should work only for limited set of Checks. For example, MethodLength check should not generate violations if user deletes lines from the method, because it makes the method 'better' for this check.

**Comment by timurt** [comment]
Can we say that for `EmptyCatchBlock` we never suppress violations (with `SuppressionXpathPatchFilter` of course and `context` strategy)?

**Comment by baratali** [comment]
> Can we say that for EmptyCatchBlock we never suppress violations (with SuppressionXpathPatchFilter of course and context strategy)?

It's better to detect DELETEs if we can, because empty `catch`es can be located in non-edited parts of the file, so it will be kind of a false-positive for context strategy.

**Comment by romani** [comment]
While we are unsure , we can make special property to keep names of Checks to should not suppress violations in deletion happened. There might be not a single Check that benefits from it, most likely all that are detecting absence of something.

**Comment by HuGanghui** [comment]
@baratali If this issue was solved in https://github.com/checkstyle/patch-filters/pull/162, is it ok to close this issue?

**Comment by baratali** [comment]
Resolved. Any new ideas/improvements should be filed as new issues.
