### ISSUE TITLE
SuppressionPatchXpathFilter: new property 'neverSuppressedChecks'

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#184]
Similar to https://github.com/checkstyle/patch-filters/issues/108, and https://github.com/checkstyle/patch-filters/issues/8#issuecomment-665565892, We need to make new property in SuppressionPatchXpathFilter like neverSuppressedChecks String[] that will have user defined list of Checks to NEVER suppress if files are touched.

**Comment by romani** [comment]
fix is merged
