### ISSUE TITLE
Remove ALWAYS_MATCHING_CONTEXT_STRATEGY_CHECKS from PatchXpathFilterElement

### ISSUE THREAD

**Issue by baratali** [checkstyle/patch-filters#222]
We should use new property `neverSuppressedChecks` which means almost the same as `ALWAYS_MATCHING_CONTEXT_STRATEGY_CHECKS`. The only difference is that `ALWAYS_MATCHING_CONTEXT_STRATEGY_CHECKS` covers only context strategy, but `neverSuppressedChecks` covers all strategies (newline/patchedline/context).
But I think it's OK for Checks from `ALWAYS_MATCHING_CONTEXT_STRATEGY_CHECKS` (OuterTypeNumber, NoCodeInFile, OuterTypeFilename) to generate violations for all strategies, not only context.

Related PR: https://github.com/checkstyle/patch-filters/pull/200

**Comment by romani** [comment]
Yes, I am ok.

**Comment by HuGanghui** [comment]
yes, I am ok too.

**Comment by romani** [comment]
Fix is merged
