### ISSUE TITLE
Add a new matching method in SuppressionPatchFilterElement to avoid suppress violations that are passed by SuppressionPatchXapthFilter

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#284]
Add a new matching method in SuppressionPatchFilterElement to avoid suppress violations that are passed by SuppressionPatchXapthFilter.

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
@romani There is not much details in this issue. Can some be provided to clarify why `SuppressionPatchFilter` needs to care about the existence of other modules like `SuppressionJavaPatchFilter` which live outside of it's scope?

This seems like a concern as main repo is adding some functionality to support new sub-modules. Does this mean things would break with using this repo alongside these new sub-modules and there is no way to support them unless `SuppressionPatchFilter` adds a registration service?

**Comment by romani** [comment]
This project is not ready to create about 3rd party modules.
We now in stage of prove of concept. Let's make it work first and then think about other modules
