### ISSUE TITLE
Fix Name bug in PatchFilter

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#29]
when I try to test and get violations through patch filter, I find a bug about name, reason is that patch filter will decide to accept an AuditEvent event according to isFileNameMatching(event) && isLineMatching(event); 
https://github.com/checkstyle/patch-filters/blob/ebd74e0b0c6040852b3486d2009c37c9352f96ba/src/main/java/com/github/checkstyle/patchfilter/SuppressionPatchFilterElement.java#L51-L54 
but I find that event.getFileName() is an absolute path, but now filename that get from patch file may not be consistent with event's absolute path, it decide to where you to do `diff` or `git format` or similar command, it is revenant path, and a subset of event's absolute path. 
So the following FileNameMatching condition need to be modified.
https://github.com/checkstyle/patch-filters/blob/ebd74e0b0c6040852b3486d2009c37c9352f96ba/src/main/java/com/github/checkstyle/patchfilter/SuppressionPatchFilterElement.java#L62-L65

**Comment by romani** [comment]
Fix is merged
