### ISSUE TITLE
 Put some rows in SuppressionPatchFilterTest and SuppressionPatchXpathFilterTest to one row

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#291]
Put some rows in SuppressionPatchFilterTest and SuppressionPatchXpathFilterTest to one row, for example :

```
 testByConfig(
                "sizes/MethodCount/newline/defaultContextConfig.xml");
```
to
`testByConfig("sizes/MethodCount/newline/defaultContextConfig.xml");`

**Comment by baratali** [comment]
Resolved in https://github.com/checkstyle/patch-filters/pull/292
(there are still some tests on multiple rows, because one line breaks 100 chars limit)
