### ISSUE TITLE
Add command line usage for patch-filter project  

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#298]
if we plan to stay patch-filter as a separate project, it necessary to add command line usage for patch-filter project? like https://github.com/checkstyle/regression-tool.  we have https://github.com/checkstyle/patch-filters/blob/master/src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFileLauncher.java, so if we want, it's ok to finish it.

**Comment by rdiachenko** [comment]
No need for this. That bit was done for testing purposes only and won't be used in other projects. What will be used is everything under `com.puppycrawl.tools.checkstyle.filters` - the work you did for integrating with eclipse-cs.
