### ISSUE TITLE
Implement checkNameForContextStrategyByTokenOrAncestorSet

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#302]
as mentioned in https://github.com/checkstyle/patch-filters/pull/167#discussion_r467586759, during solving FinalLocalVariable's context strategy, We find a good solution that specify a collection of node types which should be used for context strategy (METHOD_DEF, CTOR_DEF, VARIABLE_DEF, etc) and if a check is included to
checkNameForContextStrategyByTokenOrAncestor then we go up by AST until we find a node whose type is from context node types. So it can be its parent, or parent's parent, or further.

This solution will not only solve FinalLocalVariable's context strategy, but also will benefit other similar checks' context strategy.

**but this solution will have an effect that if one violation node's ancestor node's one child node is changed/added/deleted, we will pass this violation, maybe the changed/added/deleted child node is not relevant to this violation node. But I think it is ok, for example, one method is changed, then all violations in this method are passed is ok and good, at least better than current version: some checks only can use `neverSuppressedChecks`, which will pass all changed files's violation of this check, the scope is larger, and maybe not friendly for users. this problem is mentioned in https://github.com/checkstyle/patch-filters/issues/125**

**Comment by baratali** [comment]
Please have a look at Checks which process comments. Example: https://github.com/checkstyle/patch-filters/pull/266#issuecomment-674042911

**Comment by HuGanghui** [comment]
parent node——METHOD_DEF

* ParameterNumberCheck
* SuperClone

**Comment by HuGanghui** [comment]
All checks in https://github.com/checkstyle/patch-filters/issues/8#issuecomment-665565892 using `neverSuppressedChecks`

**Comment by HuGanghui** [comment]
All checks in https://github.com/checkstyle/patch-filters/issues/8#issuecomment-665565892  using `neverSuppressedChecks`

(these add/delete/change nodes and violation node belong to different method)

**Comment by HuGanghui** [comment]
3. the third kind of checks: All checks in https://github.com/checkstyle/patch-filters/issues/8#issuecomment-666272689  using neverSuppressedChecks

**Comment by HuGanghui** [comment]
4. the fourth kind of checks which throw only one violation for whole file, All checks in https://github.com/checkstyle/patch-filters/issues/8#issuecomment-667061679 using neverSuppressedChecks:

not work:
* OuterTypeNumberCheck (violation node is PACKAGE_DEF)
* NoCodeInFileCheck (no violation node, just `line 1`)
* OuterTypeFilename (violation node is CLASS_DEF)

**Comment by HuGanghui** [comment]
5. the fifth kind of checks, all violations' information line are the 0/1, and violation information no node, just a line information:

not works:

* NoCodeInFileCheck (no violation node, just `line 1`)
* Regexp (no violation node, just `line 0`)

**Comment by HuGanghui** [comment]
6. the sixth kind of checks, checks belong to Javadoc module do not support ast tree, All checks in https://github.com/checkstyle/patch-filters/issues/8#issuecomment-669225569 using neverSuppressedChecks:

not works:
* AtclauseOrder
* JavadocMethod
* JavadocParagraph
* SummaryJavadoc

**Comment by baratali** [comment]
@HuGanghui ,
From https://github.com/checkstyle/patch-filters/issues/302#issuecomment-674113880:

> VariableDeclarationUsageDistance (violation node has some problem)

what problem? please explain.

> ancestor node——METHOD_DEF （which means using acncestor node METHOD_DEF will works to get all violations)
> RightCurly

In RightCurly you need `try` or `if` node as I remember. METHOD_DEF can cover all other non-related violations. I think you should add `LITERAL_TRY` and `LITERAL_IF` to context nodes list. This will narrow allowed space for violations.

**Comment by baratali** [comment]
> ancestor node—— CLASS_DEF
> MissingOverride
> JavadocVariable
> MissingJavadocMethod

Those should stop on METHOD_DEF and VARIABLE_DEF. Do you know how to include comments to METHOD_DEF node when your filter works?

**Comment by HuGanghui** [comment]
Mentioned in https://github.com/checkstyle/patch-filters/issues/302#issuecomment-677675372,

>Those should stop on METHOD_DEF and VARIABLE_DEF. Do you know how to include comments to METHOD_DEF node when your filter works?

as mentioned in https://github.com/checkstyle/patch-filters/pull/133#discussion_r460449393 and https://github.com/checkstyle/patch-filters/issues/8#issuecomment-666272689 MissingOverride, JavadocVariable, MissingJavadocMethod these checks are not comments aware. No way to include comments to METHOD_DEF node except changing these Checks' `isCommentNodesRequired` from `false` to `true`.

**Comment by HuGanghui** [comment]
>>VariableDeclarationUsageDistance (violation node has some problem)
>what problem? please explain.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/50866227/91060307-5aec3d00-e65d-11ea-897b-fb039247ba11.png">

**Comment by baratali** [comment]
> as mentioned in #133 (comment) and #8 (comment) MissingOverride, JavadocVariable, MissingJavadocMethod these checks are not comments aware. No way to include comments to METHOD_DEF node except changing these Checks' isCommentNodesRequired from false to true.

OK, thanks for explanation. Let's not put these checks to CHECK_TO_ANCESTOR_NODES_MAP then, because going up to CLASS_DEF will produce violations for all other variables and methods in a class, which is false-positives for context strategy. These checks should stay in neverSuppressedChecks, to indicate that all violations would be printed.

**Comment by baratali** [comment]
> although VariableDeclarationUsageDistance have ast information log(ast, MSG_KEY_EXT, variable.getText(), dist, allowedDistance);, but from the following error information and picture, we can see that it does not have ast violation node.

Please check why eventAst is null. According to [Check's source code](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java#L330) it always logs errors for VARIABLE_DEF nodes.

**Comment by HuGanghui** [comment]
>OK, thanks for explanation. Let's not put these checks to CHECK_TO_ANCESTOR_NODES_MAP then, because going up to CLASS_DEF will produce violations for all other variables and methods in a class, which is false-positives for context strategy. These checks should stay in neverSuppressedChecks, to indicate that all violations would be printed.

@baratali yes, I take this into account, and as I said in https://github.com/checkstyle/patch-filters/issues/302#issue-679028476, please have a look and share your idea:

>but this solution will have an effect that if one violation node's ancestor node's one child node is changed/added/deleted, we will pass this violation, maybe the changed/added/deleted child node is not relevant to this violation node. But I think it is ok, for example, one method is changed, then all violations in this method are passed is ok and good, at least better than current version: some checks only can use neverSuppressedChecks, which will pass all changed files's violation of this check, the scope is larger, and maybe not friendly for users. this problem is mentioned in #125

**Comment by HuGanghui** [comment]
> Please check why eventAst is null. According to Check's source code it always logs errors for VARIABLE_DEF nodes.

@baratali the reason is that there are some checks do not update AbstractChecks to log DetailAST in checkstyle 8.33, so we need to update checkstyle dependency to 8.35, then is problem will be solved.

**Comment by baratali** [comment]
New property implemented in https://github.com/checkstyle/patch-filters/pull/303. These checks are supported for now:
 - AvoidNestedBlocks
 - FinalLocalVariable
 - RightCurly

**Comment by baratali** [comment]
@HuGanghui ,

> @baratali yes, I take this into account, and as I said in #302 (comment), please have a look and share your idea:
> 
> but this solution will have an effect that if one violation node's ancestor node's one child node is changed/added/deleted, we will pass this violation, maybe the changed/added/deleted child node is not relevant to this violation node. But I think it is ok, for example, one method is changed, then all violations in this method are passed is ok and good, at least better than current version: some checks only can use neverSuppressedChecks, which will pass all changed files's violation of this check, the scope is larger, and maybe not friendly for users. this problem is mentioned in #125 

I don't understand how this can fix #125 problem. Setting CLASS_DEF is almost the same as setting neverSuppressedChecks. Also you would need interfaces, enums and records too. So there is no difference with neverSuppressedChecks.

To support context strategy for JavadocVariable, MissingOverride, MissingJavadocMethod checks we should update them to include comments in the AST. And then we can react only on changes in VARAIBLE_DEF for JavadocVariable, and METHOD_DEF for MissingJavadocMethod/MissingOverride.

>  one method is changed, then all violations in this method are passed is ok and good, at least better than current version

Problem is that when anything in a class is changed then all violations for this class are passed. It doesn't apply only for one method.

I think we should keep neverSuppressedChecks property for these Checks for now. And update JavadocVariable, MissingOverride, MissingJavadocMethod to support comment nodes in AST (isCommentNodesRequired = true). After they are updated we can add them to CHECK_TO_ANCESTOR_NODES_MAP.
What do you think? If you agree, please create github issues in main repo https://github.com/checkstyle/checkstyle to update these Checks.

**Comment by baratali** [comment]
@HuGanghui ,
https://github.com/checkstyle/patch-filters/issues/302#issuecomment-679388538
did you check why eventAst is null?

**Comment by HuGanghui** [comment]
@baratali yes, updating checkstyle to 8.35 is to solve some checks that not support ast, which including `VariableDeclarationUsageDistance`

**Comment by HuGanghui** [comment]
>What do you think? If you agree, please create github issues in main repo https://github.com/checkstyle/checkstyle to update these Checks.

@baratali yes, I agree, but I am not sure if it's ok that changing `isCommentNodesRequired = true` do not have any compatibility problems

**Comment by baratali** [comment]
> @baratali yes, I agree, but I am not sure if it's ok that changing isCommentNodesRequired = true will not have any compatibility problems

@HuGanghui , Yes, this won't be an easy fix. I created a new issue in checkstyle: https://github.com/checkstyle/checkstyle/issues/8778
But you don't need to fix it, this issue is for future improvements. You can keep JavadocVariable, MissingJavadocMethod, MissingOverride in neverSuppressedChecks for now, and skip them in this task.

**Comment by baratali** [comment]
> @HuGanghui ,
> #302 (comment)
> I saw you updated checkstyle to 8.35. Can you add VariableDeclarationUsageDistance now?

> @baratali yes, updating checkstyle to 8.35 is to solve some checks that not support ast, which including VariableDeclarationUsageDistance

@HuGanghui , Do you have any problems with VariableDeclarationUsageDistance check? I don't see a pull request for it. Let me know if you need help.

**Comment by HuGanghui** [comment]
@baratali sorry, I forget it, I will do it later.

**Comment by baratali** [comment]
Fix for VariableDeclarationUsageDistance merged in https://github.com/checkstyle/patch-filters/pull/339.
I'm closing this issue.

**Comment by rnveach** [comment]
HuGanghui has leftover branches in https://github.com/HuGanghui/patch-filters/branches/all tied to this issue.

https://github.com/checkstyle/patch-filters/compare/master...HuGanghui:patch-filters:302-MissJ
Atleast one contains code not in this repo

**Comment by rnveach** [comment]
@romani https://github.com/checkstyle/patch-filters/blob/42c30582f1fb4e669368028e9eddfa924c12148f/src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java#L51

There is more discussions here, but I am not following why we need to build this list manually and how we identify what to put in it. It seems to be a concern to me that we need to manually build/track this for every TreeWalker check and everything could fall apart with a new release of Checkstyle. We also most likely can't support 3rd part modules again without some registration service.

If this map is required to be built and correct, I will make a new issue to expand it out as needed (automatically or manually).

**Comment by romani** [comment]
We made decision for each Check separately to define where is scope of Check - in method, in Expression, in class.

Yes, it is not very customasible, but it is strategy. If strategy proves that it works, w we can find way to make it more self discoverable from Check.
