### ISSUE TITLE
Add more details in pom.xml and publish patch-filters to maven repository?

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#306]
Do we need to add more details in pom.xml and publish patch-filters to maven repository?

**Comment by rdiachenko** [comment]
@romani you are an expert here. Any thoughts?

**Comment by romani** [comment]
I will do this.

**Comment by romani** [comment]
deployed - https://repo1.maven.org/maven2/com/puppycrawl/tools/patch-filters/

see how to setup local settings at https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#pre-reqs

commands:
```
mvn -e -Pgpg release:prepare 
mvn -e -Pgpg release:perform
```
