### ISSUE TITLE
List checks that will miss some violations when only use supportContextStrategyChecks property

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#308]
List checks that will miss some violations when only use supportContextStrategyChecks property

**Comment by rdiachenko** [comment]
@HuGanghui please clarify the description and what you are trying to achieve by this issue? The PR is in a draft stage, any reason?

**Comment by HuGanghui** [comment]
@rdiachenko because some checks listed in https://github.com/checkstyle/patch-filters/issues/8 need use `neverSuppressedChecks` or `checkNameForContextStrategyByTokenOrParentSet`, otherwise they will suppress some violations that should not be suppressed.

**Comment by rdiachenko** [comment]
The fix was merged.
