### ISSUE TITLE
Rename SuppressionPatchXpathFilter to SuppressionJavaPatchFilter

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/patch-filters#312]
`SuppressionPatchXpathFilter` is not related to xpath. Please rename it to `SuppressionJavaPatchFilter`. Also, update all `patchxpath` usages with `javapatch`. There should not be any `xpath` words in the project.

**Comment by romani** [comment]
leftovers 

```
15:41 $ ag "xpath"
README.md
43:### SuppressionPatchXpathFilter
45:Filter SuppressionPatchXpathFilter(TreeWalker level) has three different strategies that control suppression
75:For example, the following configuration fragment directs the Checker to use a SuppressionPatchXpathFilter 
84:the following configuration fragment directs the Checker to use a SuppressionPatchXpathFilter 
93:the following configuration fragment direts the Checker to use a SuppressionPatchXpathFilter 

config/checkstyle.properties
2:checkstyle.suppressions-xpath.file=config/suppressions.xml
```

@HuGanghui , please fix them also.
there should be no xpath word at all in repo

**Comment by romani** [comment]
@HuGanghui , please rebase all other PRs and rename in them also.

**Comment by HuGanghui** [comment]
@romani ok, but in `config/checkstyle.properties
2:checkstyle.suppressions-xpath.file=config/suppressions.xml` , this `xpath` is a fixed config, not introduced by this repo.

**Comment by rdiachenko** [comment]
The rest of the renaming was done in https://github.com/checkstyle/patch-filters/pull/314 and merged.
