### ISSUE TITLE
Reorganize test resources by check module

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#315]
Reorganize test resources by check module, also reorganize test methods in SuppressionJavaPatchFilterTest by check module too.

current dir:
```
suppressionjavapatchfilter
|____NestedTryDepth
|____AtclauseOrder
|____NestedForDepth
|____JavadocParagraph
|____FallThrough
```
-->
```
suppressionjavapatchfilter
|___coding
      |____NestedTryDepth
      |____NestedForDepth
      |____FallThrough
      |____NestedTryDepth
|___javadoc
      |____AtclauseOrder
      |____JavadocParagraph
```

**Comment by rdiachenko** [comment]
@HuGanghui ok to do but with a low priority if you run out of work. Please do in a single PR.

**Comment by rdiachenko** [comment]
@HuGanghui I don't see a pull request for this issue. Please do.

**Comment by HuGanghui** [comment]
OK，I will do it later.

**Comment by baratali** [comment]
Fixed in https://github.com/checkstyle/patch-filters/pull/338
