### ISSUE TITLE
make font on index.html good for usage from phone

### ISSUE THREAD

**Issue by romani** [checkstyle/patch-filters#33]
![Screenshot_20200623-065720](https://user-images.githubusercontent.com/812984/85412916-f870a680-b51e-11ea-855f-86669a43be29.png)

let make font if size same as "Checkstyle configuration report" at https://huganghui.github.io/generatePatchReport/DiffReport/guava-fb6ef19/diff/guava/index.html

**Comment by romani** [comment]
Please share prove that report is good here

**Comment by HuGanghui** [comment]
link is here: https://huganghui.github.io/html-formt/DiffReport/
