### ISSUE TITLE
 Take exact changed lines and only show violation on them, not all lines in patch file

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#37]
Now show violation on all lines shown in patch( changed and context) but we should do only only on lines with +; so we need provide functionality and test that we can take exact changed lines. We do not care about context lines, we need only changed lines.

**Comment by rdiachenko** [comment]
@HuGanghui please clarify what do you mean by `context lines`? Also, give an example of a small patch and point out what is the problem and what is expected.

**Comment by HuGanghui** [comment]
@rdiachenko you can read https://github.com/checkstyle/patch-filters/issues/31#issuecomment-648556071,https://github.com/checkstyle/patch-filters/issues/31#issuecomment-648570670 and https://github.com/checkstyle/patch-filters/issues/31#issuecomment-648574765 first, I will give a small example later.

**Comment by HuGanghui** [comment]
example is here: https://huganghui.github.io/exacted-changed-line-37/DiffReport/

**Comment by HuGanghui** [comment]
I read java-util-dff source code in master branch, and I have a general idea to solve this problem, the core is to make full use of `tag`:

https://github.com/java-diff-utils/java-diff-utils/blob/73c4c307a9cddd0cbf8155daece4aef1f74cca35/java-diff-utils/src/main/java/com/github/difflib/UnifiedDiffUtils.java#L100-L114

**Comment by rdiachenko** [comment]
@HuGanghui we can't go this way. Nobody will support your custom fork of `java-diff-utils`. Please do the following:
1. Clearly describe the problem and create an issue in `java-diff-utils`
2. Check methods inside `GeneratePatchFile` which actually generate patches and try to find a way to setup context size during patch generation

**Comment by HuGanghui** [comment]
@rdiachenko 

1. issue link is here: https://github.com/java-diff-utils/java-diff-utils/issues/89#issue-649634375

2. you can read https://github.com/checkstyle/patch-filters/issues/31#issuecomment-648574765, `diff` command have parameter and option to control context size during patch generation, but if `jgit` and `git` command such as `git show` `git diff` `git format-patch` have similar options, I am not sure now, I will research and tell you later.

**Comment by rdiachenko** [comment]
@HuGanghui I wasn't asking about `diff` command. Currently you have two methods within `GeneratePatchFile` - one uses jgit, another uses raw git diff, please find context size option for both cases.

**Comment by HuGanghui** [comment]
@rdiachenko 
1. `git diff` has options to control https://git-scm.com/docs/git-diff#Documentation/git-diff.txt--Ultngt, for example:
`git diff -U1 HEAD~1 HEAD > show1.patch`, default is 3, you can choose by `-U<n>`
2. `git show`, `git format-patch` also has https://git-scm.com/docs/git-show#Documentation/git-show.txt--Ultngt, this is a common diff option, for example `git show -U1 > show.patch`,`git format-patch -1 -U1`
3. `jgit` also have similar options according to https://www.codeaffine.com/2016/06/16/jgit-diff/

**Comment by rdiachenko** [comment]
@HuGanghui good, please update current generators to a context size = 1, so to give violations on changed/added lines only. Please do a PR in scope of this issue.

**Comment by HuGanghui** [comment]
@rdiachenko ok, I will do it

**Comment by rdiachenko** [comment]
The fix was merged

**Comment by rdiachenko** [comment]
Reopened due to https://github.com/checkstyle/patch-filters/pull/61#issuecomment-654028171

**Comment by rdiachenko** [comment]
@HuGanghui could you please revert these changes - https://github.com/checkstyle/patch-filters/pull/65/files as part of https://github.com/checkstyle/patch-filters/pull/61. Those changes were a temporary fix to avoid noise in reports. It is good to have default context and check that a new fix doesn't take unchanged lines into account.

**Comment by HuGanghui** [comment]
diff report link: https://huganghui.github.io/patch-filter-37/DiffReport/

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/50866227/87004931-cdf63d00-c1f0-11ea-899d-5260c6692acd.png">

**Comment by rdiachenko** [comment]
> @HuGanghui could you please revert these changes - https://github.com/checkstyle/patch-filters/pull/65/files as part of #61. Those changes were a temporary fix to avoid noise in reports. It is good to have default context and check that a new fix doesn't take unchanged lines into account.

Not done.

**Comment by HuGanghui** [comment]
@rdiachenko Ok, I will do it,  actually I do revert, but not add them on this PR, do we need to revert in PR ? if do,  it means in `GeneratePatchFile` 's default context is 3, not 0, this is better right?

**Comment by rdiachenko** [comment]
Please just do revert as a second commit in the current PR.

**Comment by HuGanghui** [comment]
@rdiachenko I have done, please review.

**Comment by rdiachenko** [comment]
We are going to move to JGit as java-diff-utils has a lot of restrictions. This issue is closed in favor of https://github.com/checkstyle/patch-filters/issues/76
