### ISSUE TITLE
Cannot initialize module com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/patch-filters#44]
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.205 s
[INFO] Finished at: 2020-06-25T22:44:55+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Error during page generation: Error rendering Maven report: Failed during checkstyle configuration: cannot initialize module com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter - Unable to instantiate 'com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Error during page generation
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
```
`SuppressionPatchFilter` is located under `com.github.checkstyle.patchfilter` which causes the above error. Fix checkstyle config used for testing.

**Comment by HuGanghui** [comment]
@rdiachenko yes, I mentioned in README.md that should use `com.github.checkstyle.patchfilter`

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/50866227/85937914-ac689c00-b93a-11ea-87c7-c1b48410fd99.png">

**Comment by rdiachenko** [comment]
Please use `com.puppycrawl.tools.checkstyle.filters` package, it will simplify migration into the main checkstyle project. Update README and move `SuppressionPatchFilter` and other related files into `com.puppycrawl.tools.checkstyle.filters`

**Comment by HuGanghui** [comment]
@rdiachenko I try it, and the same error in https://github.com/checkstyle/patch-filters/issues/44#issue-645872361 happens, I think the reason is that Java package or Class loading mechanism, if we change name to `com.puppycrawl.tools.checkstyle.filters`, it will be same with package name in checkstyle, and if Java Class loading mechanism not finds `SuppressionPatchFilter`, it will stop searching and error. If I wrong, please tell me.

**Comment by rdiachenko** [comment]
@HuGanghui please do:
1. Change package to `com.puppycrawl.tools.checkstyle.filter` inside `patchConfig.xml`
2. Create `com.puppycrawl.tools.checkstyle.filters` package under `src/main/java` and `src/test/java`
3. Move all files from `com.github.checkstyle.patchfilter` to `com.puppycrawl.tools.checkstyle.filters` (do for both `src/main/java` and `src/test/java`)
4. Fix `config/import-control.xml` and `config/import-control-test.xml` as follows: `<import-control pkg="(com.github.checkstyle)|(com.puppycrawl.tools.checkstyle.filters)" regex="true">`
5. Do `mvn clean install`
6. Try to build a report

I've just done these steps on my localhost and I didn't get any errors, the generated report contained `com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter` in the config section: 
![image](https://user-images.githubusercontent.com/875939/86058291-8fc28600-ba58-11ea-9d55-03d0dcfc59a5.png)


**After doing that please reply what did you miss in your attempt mentioned above and why?**

**Comment by HuGanghui** [comment]
@rdiachenko thanks, it is ok now, I think the reason of first time error is that a small mistake in package name such as should be `com.puppycrawl.tools.checkstyle.filters`, not `com.puppycrawl.tools.checkstyle.filter`

**Comment by rdiachenko** [comment]
> @rdiachenko thanks, it is ok now, I think the reason of first time error is that a small mistake in package name such as should be `com.puppycrawl.tools.checkstyle.filters`, not `com.puppycrawl.tools.checkstyle.filter`

No, it doesn't relate to this. Next time provide exact steps you did before raising the problem.

**Comment by HuGanghui** [comment]
@rdiachenko ok, I got it.

**Comment by rdiachenko** [comment]
The fix was merged.
