### ISSUE TITLE
Specify a list of commit hashes to generate report for

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/patch-filters#50]
`GeneratePatchFileLauncher`'s last parameter is the number of reports to generate for each commit starting from `HEAD`. If you give value `4` there will be 3 reports generated between each pear of commits.

The problem with this approach is that usually latest commits contain very few changes. It would be good to specify a list of commit hashes and generate reports for those commits only (the diff between the specified hash and the previous one is a patch). In this way we are free to choose any commits with a lot of code changes and use them in report analysis.

**Comment by romani** [comment]
it should be special mode, and we need to keep "HEAD .... HEAD~X" mode

**Comment by rdiachenko** [comment]
The fix was merged.
