### ISSUE TITLE
fix bugs about filename and boundary

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#54]
There is an example that only one line changed, so the startLine and endLine is same, when we change isLineMatching to
 
> result = currentLine > startLine && currentLine <= endLine;

boundary test will fail.

and after filename match condition updating, some test should be updated too.
https://github.com/checkstyle/patch-filters/blob/27fb2668fc595a8db86896adecd7a572814e0397/src/main/java/com/github/checkstyle/patchfilter/SuppressionPatchFilterElement.java#L62-L66

**Comment by rdiachenko** [comment]
The fix was merged.
