### ISSUE TITLE
extend AutomaticBean in SuppressionPatchFilter

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#55]
As mentioned in https://github.com/checkstyle/patch-filters/issues/21#issuecomment-650820623, we need to extend `AutomaticBean` in `SuppressionPatchFilter`

**Comment by rdiachenko** [comment]
@HuGanghui 
1. Fix it asap
2. How do you launch `GeneratePatchFileLauncher` and build a report if all violations are skipped without this fix?

**Comment by HuGanghui** [comment]
@rdiachenko
1. ok, I wil do it asap
2. I mentioned in https://github.com/checkstyle/patch-filters/issues/21#issuecomment-650894475

**Comment by rdiachenko** [comment]
@HuGanghui 
> I mentioned in #21 (comment)

From now on use `GeneratePatchFileLauncher` to build a report. The report generation shouldn't take more than few minutes.

**Comment by rdiachenko** [comment]
The fix was merged.
