### ISSUE TITLE
Use SupprresionPatchFilter to test checks belong to TreeWalker and generate diff reports

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#71]
>While mentors are busy to analyze report and make decision on what to do. Student should implement the same filter(line >only) but for Treewalker and generate report on guava for google-checks.xml config. - https://github.com/checkstyle/patch->filters/issues/6 

as mentioned in https://github.com/checkstyle/patch-filters/issues/6#issuecomment-656489171, according to doc, `the same filter(line only)`, do we need to use current patch filter (line) to test checks belong to Treewalker and generate diff reports? Because many TreeWalker's checks also can be correctly filtered by current patch filter (line), although now patch-filter is only line strategy, and during this process, we can find all checks that can not be correctly filtered by line strategy (doc has part of them, but maybe not full).

**Comment by romani** [comment]
@HuGanghui , please update issue description and title ... I do not understand what is "current filter".
If you mean SupprresionPatchFilter, yes we need to test how it works on Checks from TreeWalker. User might not use SupprresionPatchXpathFilter. But realistically there will be both filters in use almost always  so we need to know how they works in all combinations.
As I mentioned at https://github.com/checkstyle/patch-filters/issues/7#issuecomment-660652596, Checker filter might suppress all that passed from Treewalker filter, so we need to teach SupprresionPatchFilter how to pass all violations from certain Checks.

**Comment by HuGanghui** [comment]
The fixes were solved in https://github.com/checkstyle/patch-filters/pull/285.
