### ISSUE TITLE
Use full checkstyle run in UTs

### ISSUE THREAD

**Issue by romani** [checkstyle/patch-filters#73]
we should not use `filer.accept()` in test,
we should use same approach as in main library - full execution, check for messages. 
[we have tests](https://github.com/checkstyle/patch-filters/blob/a93897014ce3953ccd636f7d4733f1d436f85db0/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java#L40) like:
```
    public void testAccept() throws Exception {
        final String fileName = getPath("MethodCount/MethodCountPatch.txt");
        final SuppressionPatchFilter filter = createSuppressionPatchFilter(fileName);
        final LocalizedMessage message = new LocalizedMessage(7, 1, null, "msg", null,
                SeverityLevel.ERROR, null, getClass(), null);
        final AuditEvent ev = new AuditEvent(this, "MethodCountUpdate.java", message);

        assertTrue(filter.accept(ev),
                "Audit event should be rejected when there are no matching patch filters");
    }
```

we need to have test to be like:
```
    public void testAccept() throws Exception {
        final Configuration checkConfig = getConfig(getPath("MethodCount/MethodCountConfig.xml"));
        // update  checkConfig to add filter or place filter config in xml
        final String filePath = getPath("InputFileTabCharacter.java");

        final String[] expected = {
            "8:25: Line is longer than 2 characters (found 20)",
            // ..... all other violations.
        };
        verify(checkConfig, filePath, expected);
    }
```

We need to load whole config, run whole checkstyle on single file and have exact list of violations.

Please investigate how we do this in main project:
https://github.com/checkstyle/checkstyle/blob/ae9edbd4a8645c8cc1a99ad6890dd0006700d1cb/src/it/java/com/google/checkstyle/test/chapter2filebasic/rule231filetab/FileTabCharacterTest.java#L36
https://github.com/checkstyle/checkstyle/blob/739cf8e48e912fbd8ef633171a5a95e9d36e8a36/src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java#L39

Right now I see no UTs for Checker filter that you created. Please create such tests(patch, Input java file, config) for all Checks of Checker.
In #74 you will need to create manul tests, but in this issue we need to automate it.

**Comment by romani** [comment]
I did initial commit to show how to do this - https://github.com/checkstyle/patch-filters/commit/646103d50e08aef13464fda645ea765eb1ceec06 
please continue.

**Comment by rdiachenko** [comment]
Changes were merged.
