### ISSUE TITLE
Create unit tests for line strategy for Checker checks (non-TreeWalker)

### ISSUE THREAD

**Issue by baratali** [checkstyle/patch-filters#74]
"Line" strategy in SuppresionPatchFilter should pass violations only for new lines based on patch/diff file. This means that violations for the changed lines should be suppressed (filter should be able to distinguish a new line from a changed line based on a patch file).

----

Example:
Input file before changes:
```java
$ cat Input_original.java
class Input {
    public void a() {
        System.out.print("a");
    }

    public boolean b() {
        return false;
    }
}
```
Input file after changes:
```java
$ cat Input.java
class Input {
    public void a() {
        System.out.print("changed"); // no violation, because it's not a new line
    }

    public boolean b() {
        System.out.print("b"); // violation
        return false;
    }

    public void c() {
        System.out.print("c"); // violation
    }
}
```
Diff:
```diff
$ diff -Naru Input_original.java Input.java > patch.diff
$ cat patch.diff
--- Input_original.java 2020-07-12 17:01:49.228134700 +0100
+++ Input.java  2020-07-12 16:48:53.828844600 +0100
@@ -1,9 +1,14 @@
 class Input {
     public void a() {
-        System.out.print("a");
+        System.out.print("changed"); // no violation, because it's not a new line
     }

     public boolean b() {
+        System.out.print("b"); // violation
         return false;
     }
+
+    public void c() {
+        System.out.print("c"); // violation
+    }
 }
```
Checkstyle config:
```xml
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="RegexpSingleline">
    <property name="format" value="System.out.print"/>
  </module>
</module>
```
Expected checkstyle output would be following. Violation from line 3 should be suppressed:
```
Starting audit...
[ERROR] C:\Users\Baratali\git\test_checkstyle\line-strategy\Input.java:7: Line matches the illegal pattern 'System.out.print'. [RegexpSingleline]
[ERROR] C:\Users\Baratali\git\test_checkstyle\line-strategy\Input.java:12: Line matches the illegal pattern 'System.out.print'. [RegexpSingleline]
Audit done.
```

----

We need to create unit tests to test line strategy for each Checker check. Since line strategy is not implemented yet in SuppressionPatchFilter, please start creating input files, configs and expected results similar to the example above. Then we can easily create actual unit tests based on configs and expected results.
At least one test is required for each non-TreeWalker Check. Also while you generate diff reports for eclipse-cs project, please look for non-trivial cases and add them here as tests.

We need to test all possible diff cases like:
 - there are only deleted lines in patch file
 - there are only new lines in patch file
 - there are only changed lines in patch file
 - new lines in existing file vs new file
 - mixed changes - changed + deleted + new lines
 - etc...

**Comment by romani** [comment]
First example is merged. 
Hu, please continue

**Comment by HuGanghui** [comment]
@baratali there is a strange situation in `RegexpMultiline`: only one violations appears, please tell me if I'm incorrect in some place.

```java
package Checker.RegexpMultiline;

public class Test {
    void method() {
        System.out. // line 2
                print("Example"); // line3

        System.out. // line 2
                print("Example"); // line3

        System.out. // line 2
                print("Example"); // line3





        System.out. //
                print("Example");







        //// sds

        System.out. //
                print("Example");


    }
}

```
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">

    <module name="RegexpMultiline">
        <property name="matchAcrossLines" value="true"/>
        <property name="format" value="System\.out.*print\("/>
    </module>

    <!-- as we run on regression even on non-compiled files we need to skip exceptions on them -->
    <module name="SuppressionSingleFilter">
        <property name="message" value="Exception occurred while parsing"/>
        <property name="checks" value="Checker"/>
    </module>

</module>

```

```sh
Starting audit...
[ERROR] /Users/hgh/Downloads/my_file/IDEA_workspace/patchfiltergeneratepatch/src/main/java/Checker/RegexpMultiline/Test.java:5: Line matches the illegal pattern 'System\.out.*print\('. [RegexpMultiline]
Audit done.
Checkstyle ends with 1 errors.

```

**Comment by baratali** [comment]
@HuGanghui , your regexp matches all lines in the method body as one expression (`System.out` on the first line, `print(` on the last line, and `.*` is everything in between).
Please look at the example in https://checkstyle.sourceforge.io/config_regexp.html#RegexpMultiline
> Note: Beware of the greedy regular expression used in the above example. .* will match as much as possible and not produce multiple violations in the file if multiple groups of lines could match the expression. To prevent an expression being too greedy, avoid overusing matching all text or allow it to be optional, like .*?. Changing the example expression to not be greedy will allow multiple violations in the example to be found in the same file.

**Comment by HuGanghui** [comment]
@baratali thanks, I got it, I do not notice this note information, sorry.

**Comment by HuGanghui** [comment]
@baratali I think it is not necessary, and the reason is here https://github.com/checkstyle/patch-filters/issues/92#issuecomment-659295910 as same as https://github.com/checkstyle/patch-filters/issues/92

**Comment by baratali** [comment]
@HuGanghui , I meant 'any' as 'only one check', so you're right, testing one check is enough :)
I will close this issue - these remaining cases will be added in #92.
