### ISSUE TITLE
Add unit tests to evaluate jgit patch parser

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/patch-filters#76]
https://github.com/java-diff-utils/java-diff-utils has a lot of restrictions and has a very poor support of loading a patch from a text file. There is another option we need to try - JGit. It is a more mature and reliable tool.

In scope of this issue add unit tests to evaluate JGit Patch parser abilities - https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/patch/Patch.java. JGit is already included as a dependency for a patch-filters project:
```
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit</artifactId>
            <version>5.2.1.201812262042-r</version>
        </dependency>
```

Each unit test should have a patch file as an input and a bunch of assertions of a resulted Patch java object.

The following cases have to be covered:
1. Patch file contains a single file and multiple hunks within that file
2. Patch file contains multiple files and multiple hunks withing each file
3. Patch file contains file which was renamed without any changes
4. Patch file contains file which was removed
5. Patch file contains a block of code which was moved into another place within the same file without changes
6. Patch file contains a hunk which contains deletions only
7. Patch file contains a hunk which contains additions only
8. Patch file contains a hunk which contains replacements only
9. Patch file contains a hunk which contains deletions and additions and replacements within a single hunk

The following sets of unit tests are expected for each of the above point:
1. Patch is generated via `git diff <commit1> <commit2>` (using default context size) - Pull Request 1
2. Patch is generated via `git diff -U0 <commit1> <commit2>` (using context size = 0) - Pull Request 2

**Comment by rdiachenko** [comment]
@HuGanghui I removed `diff -U ... ` test suit from the issue description. You've already done both `git diff ...` in your two PRs, no additional PRs is required.

**Comment by HuGanghui** [comment]
@rdiachenko OK, I got it.

**Comment by HuGanghui** [comment]
default-size:

```java
@Test
    public void testMultiHunksOnSingleFile() throws Exception {
        final String patchName = "MultiHunksOnOneFile.patch";
        final Patch patch = loadPatch(getPatchPath(patchName));
        assertNotNull(patch);

        final List<? extends FileHeader> fileHeaders = patch.getFiles();
        assertEquals(1, fileHeaders.size());

        // file header 0
        assertEquals(FileHeader.PatchType.UNIFIED, fileHeaders.get(0).getPatchType());
        assertEquals(2, fileHeaders.get(0).getHunks().size());

        final EditList edits = fileHeaders.get(0).toEditList();
        assertEquals(2, edits.size());
        assertEquals(new Edit(4, 4, 4, 12), edits.get(0));
        assertEquals(Edit.Type.INSERT, edits.get(0).getType());
        assertEquals(new Edit(17, 17, 25, 27), edits.get(1));
        assertEquals(Edit.Type.INSERT, edits.get(1).getType());
    }
```

```
diff --git a/src/main/java/Test1.java b/src/main/java/Test1.java
index 90363f8..aeb4c5d 100644
--- a/src/main/java/Test1.java
+++ b/src/main/java/Test1.java
@@ -2,6 +2,14 @@ public class Test1 {
     public void test1() {
 
     }
+
+    public void test2() {
+
+    }
+
+    public void test3() {
+
+    }
 }
 
 
@@ -15,5 +23,7 @@ public class Test1 {
 class Test {
     public void test1() {
         System.out.println();
+        System.out.println();
+        System.out.println();
     }
 }
```

**Comment by HuGanghui** [comment]
zero-size:

```java
@Test
    public void testMultiHunksOnSingleFile() throws Exception {
        final String patchName = "MultiHunksOnOneFile.patch";
        final Patch patch = loadPatch(getPatchPath(patchName));
        assertNotNull(patch);

        final List<? extends FileHeader> fileHeaders = patch.getFiles();
        assertEquals(1, fileHeaders.size());

        // file header 0
        assertEquals(FileHeader.PatchType.UNIFIED, fileHeaders.get(0).getPatchType());
        assertEquals(2, fileHeaders.get(0).getHunks().size());

        final EditList edits = fileHeaders.get(0).toEditList();
        assertEquals(2, edits.size());
        assertEquals(new Edit(3, 3, 4, 12), edits.get(0));
        assertEquals(Edit.Type.INSERT, edits.get(0).getType());
        assertEquals(new Edit(16, 16, 25, 27), edits.get(1));
        assertEquals(Edit.Type.INSERT, edits.get(1).getType());
    }
```

```
diff --git a/src/main/java/Test1.java b/src/main/java/Test1.java
index 90363f8..aeb4c5d 100644
--- a/src/main/java/Test1.java
+++ b/src/main/java/Test1.java
@@ -4,0 +5,8 @@ public class Test1 {
+
+    public void test2() {
+
+    }
+
+    public void test3() {
+
+    }
@@ -17,0 +26,2 @@ class Test {
+        System.out.println();
+        System.out.println();

```

**Comment by HuGanghui** [comment]
although, it is the same source file and target file, but when using git diff, default-size and zero-size will make small difference in EditList's lines position.

**Comment by HuGanghui** [comment]
And EditList's startLine is from 0, is it ok, does this match with Checkstyle's violation information tradition?

**Comment by rdiachenko** [comment]
@HuGanghui 
> although, it is the same source file and target file, but when using git diff, default-size and zero-size will make small difference in EditList's lines position

As long INSERT and REPLACE edits have the same `beginB` and `endB` according to `Edit` class we are fine. And it looks like both default-size and zero-size tests have those values the same for INSERT and REPLACE edits.

> And EditList's startLine is from 0, is it ok, does this match with Checkstyle's violation information tradition?

Here we have a 0-based indexes for INSERT/REPLACE edits but Checkstyle uses 1-based indexes in violations. Please make sure to handle this in the line strategy PR.

**Comment by rdiachenko** [comment]
Fixes are merged.
