### ISSUE TITLE
Analyze dependencies jgit brings when included in the project

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/patch-filters#77]
We need to check which transitive maven dependencies JGit brings when included in the project. The less, the better. Having a list of those dependencies we will decide whether to include JGit into the project or just copy needed classes from it and put them into a patch-filters.

**Comment by romani** [comment]
https://mvnrepository.com/artifact/org.eclipse.jgit/org.eclipse.jgit/5.8.0.202006091008-r
```
org.slf4j » slf4j-api
com.googlecode.javaewah » JavaEWAH
```

https://github.com/eclipse/jgit/blob/9b033a1b6da1193dbedca80c217af748ae546629/org.eclipse.jgit/pom.xml#L38

https://mvnrepository.com/artifact/com.googlecode.javaewah/JavaEWAH/1.1.7 - (162 Kb) and it depends on nothing - GOOD.

We are good to go even when we move this Filter to main project.

But realistically - it would be much better to copy only required set of classes for us, but we will think on this at the end
