### ISSUE TITLE
testByConfig should be able to process not only single file, but also directory

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#88]
testByConfig merged in https://github.com/checkstyle/patch-filters/commit/646103d50e08aef13464fda645ea765eb1ceec06 should be able to process not only single file, but also directory, because some test input is a directory contains more than one file.

**Comment by rdiachenko** [comment]
@HuGanghui I'm trying to understand the problem you mentioned above but without success. Could you give more details?

**Comment by HuGanghui** [comment]
@rdiachenko 

> Could you give more details?

https://github.com/checkstyle/patch-filters/blob/6d05b34a5ae2aa2a65137ac448eaee034c31446e/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java#L424

https://github.com/checkstyle/patch-filters/blob/6d05b34a5ae2aa2a65137ac448eaee034c31446e/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterTest.java#L440-L444

Now testByConfig only can process single file,  if inputFile is a directory, it can not process.

**Comment by rdiachenko** [comment]
The fix was merged.
