### ISSUE TITLE
update some old UT in SuppressionPatchFilterTest because of using new JGit's parsing patch file function 

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#89]
update some old UT in SuppressionPatchFilterTest because of using new JGit's parsing patch file function.

**Comment by rdiachenko** [comment]
@HuGanghui Please clarify what do you mean and try be more specific.

**Comment by HuGanghui** [comment]
@rdiachenko 

many old UT in SuppressionPatchFilterTest is like here and they are design to test patch filter which using original java-diff-utils' parsing patch file function, now we using the new parsing patch file function provided by JGit, some UT can not be passed and need to be modified.

```java
@Test
    @Ignore("until https://github.com/checkstyle/patch-filters/issues/89")
    public void testAccept() throws Exception {
        final String fileName = getPath("MethodCount/MethodCountPatch.txt");
        final SuppressionPatchFilter filter = createSuppressionPatchFilter(fileName);
        final LocalizedMessage message = new LocalizedMessage(7, 1, null, "msg", null,
                SeverityLevel.ERROR, null, getClass(), null);
        final AuditEvent ev = new AuditEvent(this, "MethodCountUpdate.java", message);

        assertTrue(filter.accept(ev),
                "Audit event should be rejected when there are no matching patch filters");
    }
```

**Comment by rdiachenko** [comment]
Please remove such tests and related inputs. Those cases should already be covered by #73, #76, #92
